### ISSUE TITLE
您好可视化需要您指导一下

### ISSUE THREAD

**Issue by ksama777** [charlesChen02/RandLA-pytorch#7]
您好，之前复现过您的代码，现在想可视化看一下。但是它报这个错，您能帮我看看吗

python3 visualize_SemanticKITTI.py --dataset /media/wx/HDD/DQ/semantic_kitti/dataset/sequences --predictions /media/wx/HDD/DQ/RandLA-pytorch-main/result --sequence 08
********************************************************************************
INTERFACE:
Dataset /media/wx/HDD/DQ/semantic_kitti/dataset/sequences
Config /media/wx/HDD/DQ/RandLA-pytorch-main/utils/semantic-kitti.yaml
Sequence 08
Predictions /media/wx/HDD/DQ/RandLA-pytorch-main/result
********************************************************************************
Opening config file /media/wx/HDD/DQ/RandLA-pytorch-main/utils/semantic-kitti.yaml
Sequence folder exists! Using sequence from /media/wx/HDD/DQ/semantic_kitti/dataset/sequences/08/velodyne
Labels folder exists! Using labels from /media/wx/HDD/DQ/RandLA-pytorch-main/result/vis/08/predictions
Using semantics in visualizer
Traceback (most recent call last):
  File "visualize_SemanticKITTI.py", line 98, in <module>
    semantics=True, instances=False)
  File "/media/wx/HDD/DQ/RandLA-pytorch-main/utils/semkitti_vis/laserscanvis.py", line 28, in __init__
    self.update_scan()
  File "/media/wx/HDD/DQ/RandLA-pytorch-main/utils/semkitti_vis/laserscanvis.py", line 108, in update_scan
    self.scan.open_scan(self.scan_names[self.offset])
  File "/media/wx/HDD/DQ/RandLA-pytorch-main/utils/semkitti_vis/laserscan.py", line 68, in open_scan
    raise RuntimeError("Filename extension is not valid scan file.")
RuntimeError: Filename extension is not valid scan file.

我不知道我是不是哪里路径出了问题

**Comment by ksama777** [comment]
之前用的evaluate的路径是evaluate_SemanticKITTI.py --dataset /media/wx/HDD/DQ/semantic_kitti/dataset/sequences --predictions /media/wx/HDD/DQ/RandLA-pytorch-main/result --sequence 08

**Comment by Vonct** [comment]
> 之前用的evaluate的路径是evaluate_SemanticKITTI.py --dataset /media/wx/HDD/DQ/semantic_kitti/dataset/sequences --predictions /media/wx/HDD/DQ/RandLA-pytorch-main/result --sequence 08

请问你最后可视化出来了吗？我也是这个问题，我打算可视化grid_sample后的数据集，但是也是报这个错，是要evaluate之后才会生成正确的文件吗？grid后的点云和label文件都是.npy的，但是可视化需要label是.label
